### ISSUE TITLE
Move to vivo-community?

### ISSUE THREAD

**Issue by awoods** [mjaved495/VIVOPhotoDataGenerator#1]
Would it make sense to move this project over to [vivo-community](https://github.com/vivo-community)?

**Comment by mjaved495** [comment]
I was wondering who added an "issue" on this project :)
Sure. we can. How and who can do it?

**Comment by awoods** [comment]
As a committer, you should have access on vivo-community to "Transfer ownership" of this project.
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
Let me know if I can help.

**Comment by mjaved495** [comment]
Done.
