### ISSUE TITLE
People with similar localname URLs 

### ISSUE THREAD

**Issue by roflinn** [mjaved495/VIVOPhotoDataGenerator#2]
There appears to be an issue when there are people with similar localnames.

When you have someone with a localname for example of abb123 and another with abb456 it appears that the system thinks it has already processed the second image and skips it.  Maybe because a folder of abb has already been created?

Is there a way around this particular issue?  Thanks!

**Comment by mjaved495** [comment]
I will work on it.. Thanks for notifying Ralph.

**Comment by mjaved495** [comment]
I believe, i have fixed it. you can test it now.

**Comment by roflinn** [comment]
I have completed testing and everything looks good now! Thanks for the quick fix!
